include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Prefer single quotes where possible
    prefer_single_quotes: true
    
    # Prefer const constructors
    prefer_const_constructors: true
    
    # Prefer const literals as parameters of const constructors
    prefer_const_literals_to_create_immutables: true
    
    # Prefer const declarations
    prefer_const_declarations: true
    
    # Prefer const with constant constructors
    prefer_const_constructors_in_immutables: true
    
    # Prefer final for variable declarations
    prefer_final_fields: true
    
    # Prefer final for local variables
    prefer_final_locals: true
    
    # Prefer for elements in for loops
    prefer_for_elements_to_map_fromIterable: true
    
    # Prefer if elements to conditional expressions
    prefer_if_elements_to_conditional_expressions: true
    
    # Prefer initializing formal parameters
    prefer_initializing_formals: true
    
    # Prefer is not empty
    prefer_is_empty: true
    
    # Prefer is not empty
    prefer_is_not_empty: true
    
    # Prefer iterable whereType
    prefer_iterable_whereType: true
    
    # Prefer relative imports
    prefer_relative_imports: true
    
    # Prefer spread collections
    prefer_spread_collections: true
    
    # Prefer void to null
    prefer_void_to_null: true
    
    # Sort child properties last
    sort_child_properties_last: true
    
    # Sort constructors first
    sort_constructors_first: true
    
    # Sort pub dependencies
    sort_pub_dependencies: true
    
    # Sort unnamed extensions
    sort_unnamed_constructors_first: true
    
    # Use key in widget constructors
    use_key_in_widget_constructors: true
    
    # Use super parameters
    use_super_parameters: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # Treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # Allow having missing returns
    missing_return: ignore
    # Allow having unused imports
    unused_import: ignore
